/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg;

/**
 *
 * @author Raihan
 */
public class print {
    
    public void Welco(){
        
System.out.println("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█");
        OutputDelay();
System.out.println("█░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█");
        OutputDelay();
System.out.println("█░░║║║╠─║─║─║║║║║╠─░░█");
        OutputDelay();
System.out.println("█░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█");
        OutputDelay();
System.out.println("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█");
        OutputDelay();
    }
    
    public void trollface() {
        
        System.out.println("░░░░░░░░░░░░░░░░░░░▒▓▓█████████████▓▓▒░░░░░░░░░░░░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░▒████▓▓▒▒░▒▒▒░▒▒▒▒▒▒▓▓████▓▒░░░░░░░░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░▒███▓░░░░░░░░░░░░░░░░░░░░░░▒███████▓▓▒░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░▒██▓░░░░▒▒███▓▓▒░░░░░░░░░░░░░▓▓▒▒▒▒▒▓██████▓░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░▒██▓░░░▓███▓▒░░░░░░░░▒▒▒▒▒▒▒▒▒▒░░░░░░▒▓▓███▓████▒▒░░░");
        OutputDelay();
	System.out.println("░░░░░░██▓░░▒▓██▓░░▒▓██████▓░░░░░░░▒░░░░░░▒██▓▒░░░▓███▒▓▒░░░░");
        OutputDelay();
	System.out.println("░░░░░██░░▓███▒░░▒██▒░░░░▒▒██▓░░░░░░░░░░░██▒░░░░▒████▒█░░░░░░");
        OutputDelay();
	System.out.println("░░░░██░▒▓▒▓▓░░░██░░░░░░░░░░░█▓░░░░░░░░░██░░░░░░▒███░░█▒░░░░░");
        OutputDelay();
	System.out.println("░░░▓█░░░░░░░░░██░░░░░░░░░░░░▓█░░░░░░░░██░░░░░░░░░░░░░█▒░░░░░");
        OutputDelay();
	System.out.println("░░░█▓░░░░░░░░░█▒░░████░░░░░░░█▒░░░░░░░██░░░░░░░░░░░░███░░░░░");
        OutputDelay();
	System.out.println("░░▒█░░░░░░░▒▓▒█▓░▓████▓░░░░░▒█░░░░░░░░▒█▒░░░░░░░░░░██░█▒░░░░");
        OutputDelay();
	System.out.println("░░██░░░░░▒▓▒▓▒██▒▒▓▓▓░░░░░░░██░░░░░░░░░▒████▓███████▓░█▒░░░░");
        OutputDelay();
	System.out.println("░░██░░░░░▒▓▒▓▒██▒▒▓▓▓░░░░░░░██░░░░░░░░░▒████▓███████▓░█▒░░░░");
        OutputDelay();
	System.out.println("░░█▓░░░░░▒░░░▒░▒██▓▒░░░░░▒██▓░░░░░░░░░░░░░░██▓░░░░░░▒██▓░░░░");
        OutputDelay();
	System.out.println("░░█░░░░░░░░░▓▒░░░░▒▓██████▓░░░░░░░░░░░░░░▒██░░░▓█▓▓▒░░░██░░░");
        OutputDelay();
	System.out.println("░▒█░░░░░░░░░░░░░░░░░░░░░░░░░░▓▒▓▒▒▒▒▒▓▓▓▓██░░▓█▓░▒▒██▒░░██░░");
        OutputDelay();
	System.out.println("░▓█░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▓▓▒░░██░░██▓░▒░▒░██░░▒█░░");
        OutputDelay();
	System.out.println("░██░░░░░░░░░░░░░░░░░░░░░░░▒▓▒▒▒▒▒▒▒▒░░░██░░▓█░█▓░█▒█▓█▓░░█░░");
        OutputDelay();
	System.out.println("░██░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒░▒▒░░▓█▓░░██░█▒▒█▒█▒▓█░░█░░");
        OutputDelay();
	System.out.println("░██░░░░░░░░░░░░░░░░░░░░░░░░▒░░░░░░░░░░▓█░░░█▒░░░░▒▒░░▒█░▓█░░");
        OutputDelay();
	System.out.println("░▒█░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒░░█▒░░█▒░░░░░░░░▓█░█▓░░");
        OutputDelay();
	System.out.println("░░█▓░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓█░░█▒░░░░░░░░█░▒█░░░");
        OutputDelay();
	System.out.println("░░▓█░░▒░░▒▒░░▒░░░░░░░░░░░░░░░░░░░░░░░░░░█░░█▒░░░░░░░█▓░█▓░░░");
        OutputDelay();
	System.out.println("░░░█▒░░▒░░▒░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░░█░░█▒░░░░░░▓█░░█░░░░");
        OutputDelay();
	System.out.println("░░░██░░░▒░▒░░░▒▒░░░░░░░░░░░░░░░░░░░░░░░░█░░█▒░░░░░░██░░█░░░░");
        OutputDelay();
	System.out.println("░░░░█▓░░░▒░▒░░░░▒▒░░░░░▒▒▒▒▒▒░░░░░░░░░░▒█░▒█░░░░░░░█▒░░█▓░░░");
        OutputDelay();
	System.out.println("░░░░▓█░░░░▒▒░░░░░▒▒░░░░░░▒▒▒▓▓▓▒░░░░░░░██░██░░░░░░░██░░▓█░░░");
        OutputDelay();
	System.out.println("░░░░░██░░░▒░▒░░░░░▒░░░░░░░░▒░▒▒▓█▒░░░░▒█░░█▓▒▓▓▓▒░░▓█░░░█▒░░");
        OutputDelay();
	System.out.println("░░░░░▒█▒░░░▒▒▒░░░░▒░░░░░░░░░░▒▒▒░▒▓░░░██░▒█░░░░▒▓▓░░██░░█▒░░");
        OutputDelay();
	System.out.println("░░░░░░▒█▒░░░▒░▒░░░▒░░░░░░▒▒▒░░░░▒▒░░░▒█░░██░░░░░░░█░▒█░░█▒░░");
        OutputDelay();
	System.out.println("░░░░░░░▓█░░░▒░▒░░░░▒▒░░░░▓▒▒▓▓▓▒░░▓▒░██░░██▒▒▒▒▓▒▓▓███░░█▒░░");
        OutputDelay();
	System.out.println("░░░░░░░░██░░░▒░▒░░░░░▒▒░░░░░░░░▓█▓░░░█▓░░██░▓█░█░█░░█▒░░█▒░░");
        OutputDelay();
	System.out.println("░░░░░░░░░██░░░░▒▒░░░░░░▒▒░░░░░░░░▒█▓░█▓░░▓█▒▒█▒█░█▒██░░▒█░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░██▒░░░░▒░░░▒░░░▒▒░░░░░░░░▒▓██░░░██░░░░▒▒██░░░██░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░▓██░░░░░░░░▒▒░░░▒░░░░░░░░░▓█░░░░▓███▓▓██░░░██░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░▓██▒░░░░░░▒▒▒▒▒░░░░░░░░░░██░░░░░░▒▒▒░░░░██░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░▓███▒░░░░░░░▒▒▒▒▒▒▒▒░░░░▓██▒░░░░░░░▒███░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░░░▒▓███▓▒░░░░░░░▒░░▒▒▒▒░░░▒██▓██████▓░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░░░░░░░▒████▓▒▒░░░░░░░░░░░░░░░▓██▒░░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░░░░░░░░░░░▒▓████▓░░░░░░░▓█████▒░░░░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒█████████▒░░░░░░░░░░░░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒░░░░░░░░░░░░░░░░░░░░░░░");
        
    }
    public void huh(){
        
        	System.out.println("´´´´´´´´´´´´´´´´¶¶¶¶¶¶´´´´´´´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´¶¶¶´´´´´´¶¶¶´´´´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´¶´´´´´´´´´´´´¶´´´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´¶¶´´´´´´´´´´´´´´¶¶´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´¶´´´´´´´´´´´´´´´´¶¶´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´¶´´´´´´´´´´´´´´´´´´¶´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´¶´´´´´´´´´´´´´´´´´´´´¶´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´¶¶¶¶¶¶´´´¶¶¶¶¶¶´´´´´´´¶´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´¶´¶¶¶´´´´´´¶¶¶¶´´´´´´´´¶´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´¶´¶¶¶´´´´´´¶¶¶¶´´´´´´´´¶´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´¶¶¶´´´´´´¶¶¶¶´´´´´´´´´¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´¶´´¶¶¶´´´´´´¶¶¶´´´´´´´´¶¶¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´¶´´´´´´´´´´´´´´´´´´´´´´´¶¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´¶´´´´´´´´´´´´¶¶¶¶´´´´´´´´¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´¶´´´´´´´´´´¶¶¶¶¶¶¶´´´´´´´¶´´´´´´´´´´");
	System.out.println("´´´´´´´¶´´´´´´´¶¶¶¶¶¶¶¶¶¶´´´´´´´¶´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´¶´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶´´´´´¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´¶´´´´´¶¶¶¶¶¶¶¶¶¶´´¶´´´´´¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´¶´´´´´´´¶¶¶¶¶¶¶´¶´´¶´¶¶´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´¶´´´´´´´´´´´´´´´´´´´¶¶´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´¶´´´´´´´´´´´´´´´´´´¶´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´¶´´´´´´´´´´´´´´´´¶´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´¶´´´´´´´´´´´´´´¶¶´´´´´´´´´´´´´´");
        OutputDelay();
	System.out.println("´¶¶´´´´´´´´´¶¶´´´´´´´´´´´¶¶¶¶´´´´¶¶¶¶¶¶¶¶´");
        OutputDelay();
	System.out.println("´¶¶¶¶¶´´´´´´´´¶¶´´´´´´¶¶¶´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶");
        OutputDelay();
	System.out.println("´´´¶¶¶¶¶¶¶´´´´´´´´¶¶´´´´´´´¶¶¶¶¶´´´´´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´¶¶¶¶¶¶¶¶¶´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´¶¶´´¶¶¶¶¶¶´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´´´´´´´¶´´´´¶´´´´´´´¶¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´´´´´´´¶´´´´¶¶´´´´´¶´´");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´´´´´´´¶´´´´´¶´´´´´¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´´´´´´´¶´´´´´¶¶´´´´¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´´¶¶¶¶¶¶´¶´´´¶¶´´´´¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´¶¶¶¶´´´´¶¶¶¶¶´¶¶´´´´¶¶¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´¶¶¶¶¶¶¶¶¶´´´´´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶");
        OutputDelay();
	System.out.println("´´¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶´´´´¶´¶");
        OutputDelay();
	System.out.println("¶¶¶¶¶¶¶¶´´´´´´´´´´¶´´¶¶¶¶¶¶´´¶¶¶¶¶¶¶´´´¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´¶´´´´´´´´¶´´´´´¶¶¶¶´¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´¶´´´´´´¶´´´´´´´´¶¶¶¶´¶");
        OutputDelay();
	System.out.println("´´´´´´´´´´´´´´´´´´´´´¶¶¶¶¶¶´´´´´´´´´´´¶¶¶¶");
    }
    
    public void die(){
        
        System.out.println("███████████████████████████");
        OutputDelay();
System.out.println("███████▀▀▀░░░░░░░▀▀▀███████");
        OutputDelay();
System.out.println("████▀░░░░░░░░░░░░░░░░░▀████");
        OutputDelay();
System.out.println("███│░░░░░░░░░░░░░░░░░░░│███");
        OutputDelay();
System.out.println("██▌│░░░░░░░░░░░░░░░░░░░│▐██");
        OutputDelay();
System.out.println("██░└┐░░░░░░░░░░░░░░░░░┌┘░██");
        OutputDelay();
System.out.println("██░░└┐░░░░░░░░░░░░░░░┌┘░░██");
        OutputDelay();
System.out.println("██░░┌┘▄▄▄▄▄░░░░░▄▄▄▄▄└┐░░██");
        OutputDelay();
System.out.println("██▌░│██████▌░░░▐██████│░▐██");
        OutputDelay();
System.out.println("███░│▐███▀▀░░▄░░▀▀███▌│░███");
        OutputDelay();
System.out.println("██▀─┘░░░░░░░▐█▌░░░░░░░└─▀██");
        OutputDelay();
System.out.println("██▄░░░▄▄▄▓░░▀█▀░░▓▄▄▄░░░▄██");
        OutputDelay();
System.out.println("████▄─┘██▌░░░░░░░▐██└─▄████");
        OutputDelay();
System.out.println("█████░░▐█─┬┬┬┬┬┬┬─█▌░░█████");
        OutputDelay();
System.out.println("████▌░░░▀┬┼┼┼┼┼┼┼┬▀░░░▐████");
        OutputDelay();
System.out.println("█████▄░░░└┴┴┴┴┴┴┴┘░░░▄█████");
        OutputDelay();
System.out.println("███████▄░░░░░░░░░░░▄███████");
        OutputDelay();
System.out.println("██████████▄▄▄▄▄▄▄██████████");
        OutputDelay();
System.out.println("███████████████████████████");
      
        
    }
    
 
    
    public static void Cat(){
        System.out.println("──────▄▀▄─────▄▀▄");
        OutputDelay();
System.out.println("─────▄█░░▀▀▀▀▀░░█▄");
        OutputDelay();
System.out.println("─▄▄──█░░░░░░░░░░░█──▄▄");
        OutputDelay();
System.out.println("█▄▄█─█░░▀░░┬░░▀░░█─█▄▄█");
        OutputDelay();
        
    }
    public static void MicScream(){
        System.out.println("─────────────────────────────▄██▄");
        OutputDelay();
System.out.println("─────────────────────────────▀███");
        OutputDelay();
System.out.println("────────────────────────────────█");
        OutputDelay();
System.out.println("───────────────▄▄▄▄▄────────────█");
        OutputDelay();
System.out.println("──────────────▀▄────▀▄──────────█");
        OutputDelay();
System.out.println("──────────▄▀▀▀▄─█▄▄▄▄█▄▄─▄▀▀▀▄──█");
        OutputDelay();
System.out.println("─────────█──▄──█────────█───▄─█─█");
        OutputDelay();
System.out.println("─────────▀▄───▄▀────────▀▄───▄▀─█");
        OutputDelay();
System.out.println("──────────█▀▀▀────────────▀▀▀─█─█");
        OutputDelay();
System.out.println("──────────█───────────────────█─█");
        OutputDelay();
System.out.println("▄▀▄▄▀▄────█──▄█▀█▀█▀█▀█▀█▄────█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█────█──█████████████▄───█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█────█──██████████████▄──█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█────█───██████████████▄─█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█────█────██████████████─█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█────█───██████████████▀─█─█");
        OutputDelay();
System.out.println("█▒▒▒▒█───██───██████████████──█─█");
        OutputDelay();
System.out.println("▀████▀──██▀█──█████████████▀──█▄█");
        OutputDelay();
System.out.println("──██───██──▀█──█▄█▄█▄█▄█▄█▀──▄█▀");
        OutputDelay();
System.out.println("──██──██────▀█─────────────▄▀▓█");
        OutputDelay();
System.out.println("──██─██──────▀█▀▄▄▄▄▄▄▄▄▄▀▀▓▓▓█");
        OutputDelay();
System.out.println("──████────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──███─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──██─────────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──██────────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
System.out.println("──██───────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌");
        OutputDelay();
System.out.println("──██──────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌");
        OutputDelay();
System.out.println("──██─────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌");
        OutputDelay();
System.out.println("──██────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▌");
        OutputDelay();

        
    }
    
    
    public static void JackyHuh(){
        System.out.println("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
        OutputDelay();
System.out.println("░░░░░░░░░░░░░░░░▄▄███▄▄▄░▄▄██▄░░░░░░░");
        OutputDelay();
System.out.println("░░░░░░░░░██▀███████████████▀▀▄█░░░░░░");
        OutputDelay();
System.out.println("░░░░░░░░█▀▄▀▀▄██████████████▄░░█░░░░░");
        OutputDelay();
System.out.println("░░░░░░░█▀▀░▄██████████████▄█▀░░▀▄░░░░");
        OutputDelay();
System.out.println("░░░░░▄▀░░░▀▀▄████████████████▄░░░█░░░");
        OutputDelay();
System.out.println("░░░░░▀░░░░▄███▀░░███▄████░████░░░░▀▄░");
        OutputDelay();
System.out.println("░░░▄▀░░░░▄████░░▀▀░▀░░░░░░██░▀▄░░░░▀▄");
        OutputDelay();
System.out.println("░▄▀░░░░░▄▀▀██▀░░░░░▄░░▀▄░░██░░░▀▄░░░░");
        OutputDelay();
System.out.println("█░░░░░█▀░░░██▄░░░░░▀▀█▀░░░█░░░░░░█░░░");
        OutputDelay();
System.out.println("█░░░▄▀░░░░░░██░░░░░▀██▀░░█▀▄░░░░░░▀▀▀");
        OutputDelay();
System.out.println("▀▀▀▀░▄▄▄▄▄▄▀▀░█░░░░░░░░░▄█░░█▀▀▀▀▀█░░");
        OutputDelay();
System.out.println("░░░░█░░░▀▀░░░░░░▀▄░░░▄▄██░░░█░░░░░▀▄░");
        OutputDelay();
System.out.println("░░░░█░░░░░░░░░░░░█▄▀▀▀▀▀█░░░█░░░░░░█░");
        OutputDelay();
System.out.println("░░░░▀░░░░░░░░░░░░░▀░░░░▀░░░░▀░░░░░░░░");
        OutputDelay();
System.out.println("░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░");
        OutputDelay();

        
    }
    
    public static void JokerFace(){
       	System.out.println("███████▓█████▓▓╬╬╬╬╬╬╬╬▓███▓╬╬╬╬╬╬╬▓╬╬▓█ ");
        OutputDelay();
	System.out.println("████▓▓▓▓╬╬▓█████╬╬╬╬╬╬███▓╬╬╬╬╬╬╬╬╬╬╬╬╬█ ");
        OutputDelay();
	System.out.println("███▓▓▓▓╬╬╬╬╬╬▓██╬╬╬╬╬╬▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("████▓▓▓╬╬╬╬╬╬╬▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("███▓█▓███████▓▓███▓╬╬╬╬╬╬▓███████▓╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("████████████████▓█▓╬╬╬╬╬▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬█ ");
        OutputDelay();
	System.out.println("███▓▓▓▓▓▓▓╬╬▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("████▓▓▓╬╬╬╬▓▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("███▓█▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("█████▓▓▓▓▓▓▓▓█▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█ ");
        OutputDelay();
	System.out.println("█████▓▓▓▓▓▓▓██▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██ ");
        OutputDelay();
	System.out.println("█████▓▓▓▓▓████▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██ ");
        OutputDelay();
	System.out.println("████▓█▓▓▓▓██▓▓▓▓██╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██ ");
        OutputDelay();
	System.out.println("████▓▓███▓▓▓▓▓▓▓██▓╬╬╬╬╬╬╬╬╬╬╬╬█▓╬▓╬╬▓██ ");
        OutputDelay();
	System.out.println("█████▓███▓▓▓▓▓▓▓▓████▓▓╬╬╬╬╬╬╬█▓╬╬╬╬╬▓██ ");
        OutputDelay();
	System.out.println("█████▓▓█▓███▓▓▓████╬▓█▓▓╬╬╬▓▓█▓╬╬╬╬╬╬███ ");
        OutputDelay();
	System.out.println("██████▓██▓███████▓╬╬╬▓▓╬▓▓██▓╬╬╬╬╬╬╬▓███ ");
        OutputDelay();
	System.out.println("███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬████ ");
        OutputDelay();
	System.out.println("███████▓▓██▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓████ ");
        OutputDelay();
	System.out.println("████████▓▓▓█████▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█████ ");
        OutputDelay();
	System.out.println("█████████▓▓▓█▓▓▓▓▓███▓╬╬╬╬╬╬╬╬╬╬╬▓██████ ");
        OutputDelay();
	System.out.println("██████████▓▓▓█▓▓▓╬▓██╬╬╬╬╬╬╬╬╬╬╬▓███████ ");
        OutputDelay();
	System.out.println("███████████▓▓█▓▓▓▓███▓╬╬╬╬╬╬╬╬╬▓████████ ");
        OutputDelay();
	System.out.println("██████████████▓▓▓███▓▓╬╬╬╬╬╬╬╬██████████ ");
        OutputDelay();
	System.out.println("███████████████▓▓▓██▓▓╬╬╬╬╬╬▓███████████");
        OutputDelay();
    }
    
    public static void WaitWhat(){
        	System.out.println("─────────────────▄▄▄▄▄▄▄▄▄▄▄");
        OutputDelay();
	System.out.println("────────────▄▄▀▀▀░░░░░░░░░░░▀▄▄");
        OutputDelay();
	System.out.println("────────▄▄▀▀░░░░░░░▄▄▄▄▄▄▄░░░░░▀▄");
        OutputDelay();
	System.out.println("──────▄▀░░░░░░░░░▄▄▄▄▄▄▄▄▄▄▄░░░░░█");
        OutputDelay();
	System.out.println("────▄▀░░░░░▄▄▄▄▄▄▄░░░░░░░░░░░▄▄▄▄▄█▄▄");
        OutputDelay();
	System.out.println("───▄▀░▐▌░░░░░░░░░░▀▀░░░░░░░▀▀░░░░░░█");
        OutputDelay();
	System.out.println("──█░░░▀░░░░░░░▄▀▀▀▄░░░░▄░░░░▄▀▀▀▄░░▐▌");
        OutputDelay();
	System.out.println("─█░░░░░░▄▄▄░░▐░░▄░░▌░░░░▀▄░▐░░▄░░▌░░█");
        OutputDelay();
	System.out.println("▐▌░░░░▀▀░░░░▄░▀▄▄▄▀░░░░░░░▌░▀▄▄▄▀░░░▐▌");
        OutputDelay();
	System.out.println("█░░░░░░░░░░░░▀▄▄▄░░░░░░░░▐░░░░░▄▄▄▀░░█");
        OutputDelay();
	System.out.println("█░░░░▄▀░░░░░░░▄▄░░░░░░▄▀░▐░░░▄▄░░░░░░█");
        OutputDelay();
	System.out.println("▐▌░░▀░░░░░░░▄▀░░░▐▀░░░░░░░▀▌░░░▀▄░░░░█");
        OutputDelay();
	System.out.println("▐▌░░░▐░░░░░▐▌░░░░░▀█░░░░░░░▌░░░░█░░░░█");
        OutputDelay();
	System.out.println("─█░░░░░░░░░░░░░░▄░░▀▀▄▄▄▄▀▀░▀▄░░░░░░░█");
        OutputDelay();
	System.out.println("─▐▌░░░░░░░░░░░▄▀░░░░▄▄▄▄▄▄░░░░▌░░░░░░█");
        OutputDelay();
	System.out.println("──█░░░░░░░░░░▐░░░░▄▀░░░░░░▀▄░░▌░░░░░▐▌");
        OutputDelay();
	System.out.println("──▐▌░░░░░░░░░▐░░░░▀░░░▀▀░░░▀░░░░░░░░█");
        OutputDelay();
	System.out.println("───█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▐▌");
        OutputDelay();
	System.out.println("────▀▄░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▀");
        OutputDelay();
	System.out.println("──────▀▄░░░░░░░░░░░░░░░░░░░░░░░▄▀");
        OutputDelay();
	System.out.println("────────▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀");
        OutputDelay();
    }
    
    public static void MicHold(){
        	System.out.println("──────────▄▀▀▀▀▀▀▄");
        OutputDelay();
	System.out.println("───────────▀▄─────▀▄───▄███▄");
        OutputDelay();
	System.out.println("─────────────▀▄▀▀▀▀▀▀▀▀█▀██▐█");
        OutputDelay();
	System.out.println("────────────▄▀─────────███▄██▄");
        OutputDelay();
	System.out.println("────────▄████▄──────────▀██▀─▀█");
        OutputDelay();
	System.out.println("────────█▌█▄██────────────────█▌");
        OutputDelay();
	System.out.println("────────▀█▄██▀─▄█████████▄─────█");
        OutputDelay();
	System.out.println("──────────█───██▀───────▀██────█");
        OutputDelay();
	System.out.println("▄▀▄▄▀▄────█──██───────────██───█");
        OutputDelay();
	System.out.println("█▒▒▒▒█────█──█─────────────█───█");
        OutputDelay();
	System.out.println("█▒▒▒▒█────█──▀─────────────▀───█");
        OutputDelay();
	System.out.println("█▒▒▒▒█────█────────────────────█");
        OutputDelay();
	System.out.println("█▒▒▒▒█────█────────────────────█");
        OutputDelay();
	System.out.println("█▒▒▒▒█────█───────────────────▐█");
        OutputDelay();
	System.out.println("█▒▒▒▒█───██───────────────────█▌");
        OutputDelay();
	System.out.println("▀████▀──██▀█──────────────────██");
        OutputDelay();
	System.out.println("──██───██──▀█───────────────▄███");
        OutputDelay();
	System.out.println("──██──██────▀█────────────▄▀▓▓██");
        OutputDelay();
	System.out.println("──██─██──────▀█▀▄▄▄▄▄▄▄▄▄▀▓▓▓▓██");
        OutputDelay();
	System.out.println("──████────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓███");
        OutputDelay();
	System.out.println("──███─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓█");
        OutputDelay();
	System.out.println("──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓█");
        OutputDelay();
	System.out.println("──██──────────█▓▓▓▓▓▓▓▓▓▓▓▓▓██▓█");
        OutputDelay();
	System.out.println("──██─────────▐█▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓█");
        OutputDelay();
	System.out.println("──██─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓█");
        OutputDelay();
	System.out.println("──██─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓█");
        OutputDelay();
	System.out.println("──██─────────█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█");
        OutputDelay();
    }
    
    public static void Sad(){
        	System.out.println("░░░░░░░░░░▄▄█▀▀▀▀▀▀▀▀█▄▄░░░░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░▄▄▀▀░░░░░░░░░░░░▀▀▄▄░░░░░");
        OutputDelay();
	System.out.println("░░░░░▄█▀░░░░▄▀░░░░▄░░░░░░░▀█░░░░");
        OutputDelay();
	System.out.println("░░░░██▄▄████░░░░░░▀▄░░░░░░░░█▄░░");
        OutputDelay();
	System.out.println("░░▄████▀███▄▀▄░░░░░░███▄▄▄▄░░█░░");
        OutputDelay();
	System.out.println("░▄█████▄████░██░░░▄███▄▄░▀█▀░░█░");
        OutputDelay();
	System.out.println("▄███████▀▀░█░▄█░▄███▀█████░█░░▀▄");
        OutputDelay();
	System.out.println("█░█▀██▄▄▄▄█▀░█▀█▀██████▀░██▀█░░█");
        OutputDelay();
	System.out.println("█░█░▀▀▀▀▀░░░█▀░█░███▀▀░░▄█▀░█░░█");
        OutputDelay();
	System.out.println("█░░█▄░░░░▄▄▀░░░█░▀██▄▄▄██▀░░█▄░█");
        OutputDelay();
	System.out.println("█░░░░▀█▀▀▀░░░░░░█░░▀▀▀▀░░░░▄█░░█");
        OutputDelay();
	System.out.println("█░░░░░░░░░░░░░░░░▀▄░░░░░░▄█▀░░░█");
        OutputDelay();
	System.out.println("░█░░░░░░░░░░░░░░░░▀▀▀▀▀▀▀▄░░░░█░");
        OutputDelay();
	System.out.println("░░█░░░░░░▄▄▄▄▄▄▄░░░░░░░░░░░░░▄▀░");
        OutputDelay();
	System.out.println("░░░▀▄░░░░░▀█▄░░░▀▀██▄░░░░░░░▄▀░░");
        OutputDelay();
	System.out.println("░░░░░▀▄▄░░░░░▀▀▀▀▀░░░░░░░░▄▀░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░▀▀▄▄▄░░░░░░░░▄▄▄▀▀█░░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░░▄▀▀█████▀▀▀▀░░░░██░░░░");
        OutputDelay();
	System.out.println("░░░░░░░░░█░░░██░░░█▀▀▀▀▀▀▀▀█░░░░");
        OutputDelay();

    }
    
    public static void MarioJump(){
        	System.out.println("___________________▄▄▄▀▀▀▀▀▀▀▄");
        OutputDelay();
	System.out.println(" _______________▄▀▀____▀▀▀▀▄____█");
        OutputDelay();
	System.out.println(" ___________▄▀▀__▀▀▀▀▀▀▄___▀▄___█");
        OutputDelay();
	System.out.println(" __________█▄▄▄▄▄▄_______▀▄__▀▄__█");
        OutputDelay();
	System.out.println(" _________█_________▀▄______█____█_█");
        OutputDelay();
	System.out.println(" ______▄█_____________▀▄_____▐___▐_▌");
        OutputDelay();
	System.out.println(" ______██_______________▀▄___▐_▄▀▀▀▄");
        OutputDelay();
	System.out.println(" ______█________██_______▌__▐▄▀______█");
        OutputDelay();
	System.out.println(" ______█_________█_______▌__▐▐________▐");
        OutputDelay();
	System.out.println(" _____▐__________▌_____▄▀▀▀__▌_______▐_____________▄▄▄▄▄▄");
        OutputDelay();
	System.out.println(" ______▌__________▀▀▀▀________▀▀▄▄▄▀______▄▄████▓▓▓▓▓▓▓███▄");
        OutputDelay();
	System.out.println(" ______▌____________________________▄▀__▄▄█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄");
        OutputDelay();
	System.out.println(" ______▐__________________________▄▀_▄█▓▓▓▓▓▓▓▓▓▓_____▓▓____▓▓█▄");
        OutputDelay();
	System.out.println(" _______▌______________________▄▀_▄█▓▓▓▓▓▓▓▓▓▓▓____▓▓_▓▓_▓▓__▓▓█");
        OutputDelay();
	System.out.println(" _____▄▀▄_________________▄▀▀▌██▓▓▓▓▓▓▓▓▓▓▓▓▓__▓▓▓___▓▓_▓▓__▓▓█");
        OutputDelay();
	System.out.println(" ____▌____▀▀▀▄▄▄▄▄▄▄▄▀▀___▌█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓__▓________▓▓___▓▓▓█");
        OutputDelay();
	System.out.println(" _____▀▄_________________▄▀▀▓▓▓▓▓▓▓▓█████████████▄▄_____▓▓__▓▓▓█");
        OutputDelay();
	System.out.println(" _______█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓▓▓▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▄▄___▓▓▓▓▓█");
        OutputDelay();
	System.out.println(" _______█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓▓███▓▓▓▓████▓▓▓▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓▓█");
        OutputDelay();
	System.out.println(" ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓█▓▓██░░███████░██▓▓▓▓▓▓▓▓▓▓██▓▓▓▓▓█");
        OutputDelay();
	System.out.println(" ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓██▓░░░░░█░░░░░██░░░░██▓▓▓▓▓▓▓▓▓██▓▓▓▓▌");
        OutputDelay();
	System.out.println(" ________█▓▓▓▓▓▓▓▓▓▓▓▓▓▓███░░░░░░░░____░██░░░░░░░██▓▓▓▓▓▓▓██▓▓▌");
        OutputDelay();
	System.out.println(" ________▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░░░________░░░░░░░░░██████▓▓▓▓▓█▓▌");
        OutputDelay();
	System.out.println(" ________▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░░___▓▓▓▓▓░░░░░░░███░░███▓▓▓▓▓█▓▌");
        OutputDelay();
	System.out.println(" _________█▓▓▓▓▓▓▓▓▓▓▓▓▓██░░░░░___▓▓█▄▄▓░░░░░░░░___░░░░█▓▓▓▓▓█▓▌");
        OutputDelay();
	System.out.println(" _________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░░█░░░___▓▓██░░░░░░░░▓▓▓▓__░░░░█▓▓▓▓██");
        OutputDelay();
	System.out.println(" _________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░███░░____▓░░░░░░░░░░░█▄█▓__░░░░█▓▓█▓█");
        OutputDelay();
	System.out.println(" _________▐▓▓▓▓▓▓▓▓▓▓▓▓▓█░█████░░░░░░░░░░░░░░░░░█▓__░░░░███▓█");
        OutputDelay();
	System.out.println(" __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░███████░░░░░░░░░░░░░░░▓_░░░░░██▓█");
        OutputDelay();
	System.out.println(" __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░███████░░░░░░░░░░░░░░_░░░░░██▓█");
        OutputDelay();
	System.out.println(" __________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░███████░░░░░░░░░░░░░░░░░░░██▓█");
        OutputDelay();
	System.out.println(" ___________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░░███████░░░░░░░░░░░█████░██░░░");
        OutputDelay();
	System.out.println(" ___________█▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░__███████░░░░░███████░░█░░░░");
        OutputDelay();
	System.out.println(" ___________█▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░█▄▄▄▀▀▀▀████████████░░█░░░░");
        OutputDelay();
	System.out.println(" ___________▐▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░██████▄__▀▀░░░███░░░░░█░░░");
        OutputDelay();
	System.out.println(" ___________▐▓▓▓▓▓▓▓▓▓▓▓█▒█░░░░░░▓▓▓▓▓███▄░░░░░░░░░░░░░░░______▄▄▄");
        OutputDelay();
	System.out.println(" ___________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█░░░░░░▓▓▓▓▓█░░░░░░░░░░░░░░░▄▄▄_▄▀▀____▀▄");
        OutputDelay();
	System.out.println(" __________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█▓▓░░░░░░░░░░░░░░░░░░░░░____▄▀____▀▄_________▀▄");
        OutputDelay();
	System.out.println(" _________█▓▓▓▓▓▓▓▓▓█▒▒▒▒█▓▓▓▓░░░░░░░░░░░░░░░░░______▐▄________█▄▄▀▀▀▄__█");
        OutputDelay();
	System.out.println(" ________█▓▓▓▓▓▓▓▓█▒▒▒▒▒▒█▓▓▓▓▓▓▓░░░░░░░░░____________█_█______▐_________▀▄▌");
        OutputDelay();
	System.out.println(" _______█▓▓▓▓▓▓▓▓█▒▒▒▒▒▒███▓▓▓▓▓▓▓▓▓▓▓█▒▒▄___________█__▀▄____█____▄▄▄____▐");
        OutputDelay();
	System.out.println(" ______█▓▓▓▓▓▓▓█_______▒▒█▒▒██▓▓▓▓▓▓▓▓▓▓█▒▒▒▄_________█____▀▀█▀▄▀▀▀___▀▀▄▄▐");
        OutputDelay();
	System.out.println(" _____█▓▓▓▓▓██▒_________▒█▒▒▒▒▒███▓▓▓▓▓▓█▒▒▒██________▐_______▀█_____________█");
        OutputDelay();
	System.out.println(" ____█▓▓████▒█▒_________▒█▒▒▒▒▒▒▒▒███████▒▒▒▒██_______█_______▐______▄▄▄_____█");
        OutputDelay();
	System.out.println(" __█▒██▒▒▒▒▒▒█▒▒____▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒____▒█▓█__▄█__█______▀▄▄▀▀____▀▀▄▄█");
        OutputDelay();
	System.out.println(" __█▒▒▒▒▒▒▒▒▒▒█▒▒▒████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▓▓█▓▓▌_▐________▐____________▐");
        OutputDelay();
	System.out.println(" __█▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒_______█▓▓▓█▓▌__▌_______▐_____▄▄____▐");
        OutputDelay();
	System.out.println(" _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒_____█▓▓▓█▓▓▌__▌_______▀▄▄▀______▐");
        OutputDelay();
	System.out.println(" _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███████▓▓█▓▓▓▌__▀▄_______________▄▀");
        OutputDelay();
	System.out.println(" _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒██▓▓▓▓▓▌___▀▄_________▄▀▀");
        OutputDelay();
	System.out.println(" █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒█▓▓▓▓▓▀▄__▀▄▄█▀▀▀");
        OutputDelay();
	System.out.println(" █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▓▓▓▓██▄▄▄▀");
        OutputDelay();
	System.out.println(" █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒████");
        OutputDelay();
	System.out.println(" █▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▄▄▄▄▄");
        OutputDelay();
	System.out.println(" _█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒██▄▄");
        OutputDelay();
	System.out.println(" __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒███▒▒▒▒▒▒▒▒▒▒▒▒▒█▄");
        OutputDelay();
	System.out.println(" __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" __█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" ___█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒▌");
        OutputDelay();
	System.out.println(" ____█▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒▒▒▒█▒▒▒▒█▒▒▒▒▒▒█▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░▒▒▌");
        OutputDelay();
	System.out.println(" ____█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█████████████▒▒▒▒▒█▒▒▒▒▒▒▒▒░░░░▒▒▒▒▒▒▒▒▒▒▒░▒▌");
        OutputDelay();
	System.out.println(" _____█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______▐▒▒▒▒█▒▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌");
        OutputDelay();
	System.out.println(" ______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒█▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌");
        OutputDelay();
	System.out.println(" _______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒█▒▒▒▒▒▒░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▌");
        OutputDelay();
	System.out.println(" ________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█________█▒▒▒░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▀");
        OutputDelay();
	System.out.println(" __________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒░░░▒▒▒▒▒░░░░░░░░▒▒▒█▀▀▀");
        OutputDelay();
	System.out.println(" ___________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█░▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░█▀");
        OutputDelay();
	System.out.println(" ____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█▀");
        OutputDelay();
	System.out.println(" _____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______█▒▒▒▒▒▒▒▒▒▒▒▒█▀");
        OutputDelay();
	System.out.println(" _____________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█_______▀▀▀███████▀▀");
        OutputDelay();
	System.out.println(" ______________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _______________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" ________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" __________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██▒█");
        OutputDelay();
	System.out.println(" ___________________█▒▒▒▒▒▒▒▒▒▒▒▒▒██▒▒▒▒█");
        OutputDelay();
	System.out.println(" ___________________█▒▒▒▒▒▒▒▒████▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" ___________________█████████▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" ____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" ____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█");
        OutputDelay();
	System.out.println(" _____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌");
        OutputDelay();
	System.out.println(" _____________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▌");
        OutputDelay();
	System.out.println(" ______________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▌");
        OutputDelay();
	System.out.println(" _______________________█▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░█");
        OutputDelay();
	System.out.println(" ________________________█▒▒▒▒▒▒▒▒▒▒▒░░░█");
        OutputDelay();
	System.out.println(" __________________________██▒▒▒▒▒▒░░░█▀");
        OutputDelay();
	System.out.println(" _____________________________█░░░░░█▀");
        OutputDelay();
	System.out.println(" _______________________________▀▀▀▀");
        OutputDelay();

    }
    
    public static void HappyHi(){
    System.out.println("_______§§_____§§§___§§§____§§§___§________§§");
        OutputDelay();
System.out.println("______§__§___§_____§___§__§___§__§_______§__§");
        OutputDelay();
System.out.println("______§__§___§_____§___§__§___§__§_______§__§");
        OutputDelay();
System.out.println("______§__§____§§§___§§§____§§§___§§§§____§__§");
        OutputDelay();
System.out.println("_§§____§__§_____________________________§__§____§§");
        OutputDelay();
System.out.println("§__§___§__§_____________________________§__§___§__§");
        OutputDelay();
System.out.println("§___§__§__§_____________________________§__§__§___§");
        OutputDelay();
System.out.println("_§___§__§__§___________________________§__§__§___§");
        OutputDelay();
System.out.println("__§___§§§§§§§_________________________§§§§§§§___§");
        OutputDelay();
System.out.println("___§____§___§_________________________§___§____§");
        OutputDelay();
System.out.println("____§§§§_____§_______________________§_____§§§§");
        OutputDelay();
System.out.println("___§___§__§§_§_________§§§§§_________§_§§__§___§");
        OutputDelay();
System.out.println("___§___§__§__§_______§§_____§§_______§__§__§___§");
        OutputDelay();
System.out.println("____§§§§§§___§______§_________§______§___§§§§§§");
        OutputDelay();
System.out.println("____§___§___§_§____§__8____8___§____§_§___§___§");
        OutputDelay();
System.out.println("_____§§§___§___§___§___________§___§___§___§§§");
        OutputDelay();
System.out.println("________§§§§§___§_§_____________§_§___§§§§§");
        OutputDelay();
System.out.println("_____________§§__§§_§§§§§§§§§§§_§§__§§");
        OutputDelay();
System.out.println("_______________§__§_§__§___§__§_§__§");
        OutputDelay();
System.out.println("________________§_§_§__§___§__§_§_§");
        OutputDelay();
System.out.println("_________________§§_§__§___§__§_§§");
        OutputDelay();
System.out.println("__________________§§_§_§___§_§_§§");
        OutputDelay();
System.out.println("___________________§__§§$0n§§__§");
        OutputDelay();
System.out.println("____________________§__§§§§§__§");
        OutputDelay();
System.out.println("_____________________§§_____§§");
        OutputDelay();
System.out.println("_______________________§§§§§");
        OutputDelay();

    
    }
    
    public static void Okay(){
        System.out.println("´´´´´´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶");
        OutputDelay();
System.out.println("´´´´´´´´´´´´´´´´´´´´¶¶´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´´¶¶¶¶¶´´´´´´´¶¶´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´¶´´´´´¶´´´´¶¶´´´´´¶¶´´´´¶¶´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´¶´´´´´¶´´´¶¶´´´´´´¶¶´´´´¶¶´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´¶´´´´¶´´¶¶´´´´´´´´¶¶´´´´¶¶´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´´¶´´´¶´´´¶´´´´´´´´´´´´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´¶´´´´´´´´´´´´¶´¶¶´´´´´´´´´´´´´¶¶´´´´´¶¶");
        OutputDelay();
System.out.println("´´¶¶´´´´´´´´´´´´¶´´¶¶´´´´´´´´´´´´¶¶´´´´´¶¶");
        OutputDelay();
System.out.println("´¶¶´´´¶¶¶¶¶¶¶¶¶¶¶´´´´¶¶´´´´´´´´¶¶´´´´´´´¶¶");
        OutputDelay();
System.out.println("´¶´´´´´´´´´´´´´´´¶´´´´´¶¶¶¶¶¶¶´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´¶¶´´´´´´´´´´´´´´¶´´´´´´´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´¶´´´¶¶¶¶¶¶¶¶¶¶¶¶´´´´´´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´¶¶´´´´´´´´´´´¶´´¶¶´´´´´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´¶¶¶¶¶¶¶¶¶¶¶¶´´´´´¶¶´´´´´´´´´´´´¶¶");
        OutputDelay();
System.out.println("´´´´´´´´´´´´´´´´´´´´´´´¶¶¶¶¶¶¶¶¶¶¶");
        OutputDelay();
    }
    
    public static void OutputDelay(){
     try{
            Thread.sleep(50);
        }
    catch(InterruptedException ex){
        }
    
     }
    
}
